import type { MissionId } from '../types';
import type { SecretId } from '../systems/Secrets';

// Reward lore for the Sticker Book. Each sticker a child collects becomes a small,
// re-readable poem they can revisit with a parent — "I got 3 stars" becomes a little
// story of what that meant. The childPoem/parentNote text was generated by the Grok
// model (best-of-n curated) in the project's warm, wonder-over-praise voice and lightly
// reviewed. Sticker ids match the ones the missions and Secrets actually unlock.

export type StickerSource =
  | { kind: 'mission'; id: MissionId }
  | { kind: 'secret'; id: SecretId };

export type StickerDefinition = {
  /** Matches the id stored in profile.progress.stickers. */
  id: string;
  title: string;
  /** A few short lines a parent reads aloud. No hard words. */
  childPoem: string;
  /** One warm sentence for the grown-up. */
  parentNote: string;
  icon: string;
  source: StickerSource;
};

export const STICKER_DEFINITIONS: StickerDefinition[] = [
  {
    id: 'recycling-run-starter',
    title: 'Rivet Makes Wonders',
    childPoem: 'Little scraps whisper what they might be\nRivet listens, then starts to build\nA bottle rains bubbles, a can sings moonlight\nOld things wake up wonderfully willed',
    parentNote: 'A quiet celebration of reuse as imagination: noticing hidden possibility in old things and making something helpful, funny, and new.',
    icon: 'hl.ui.recycle',
    source: { kind: 'mission', id: 'recycling-run' },
  },
  {
    id: 'house-builder-starter',
    title: 'Brick Builds a Home',
    childPoem: 'A patch of earth waits with open arms\nBrick chooses the pieces with care\nWalls rise like a story being told\nA roof closes it warm, and a light appears there',
    parentNote: 'It honors the patient joy of building something real, one thoughtful choice at a time, so someone else has a safe place to be.',
    icon: 'hl.ui.build',
    source: { kind: 'mission', id: 'house-builder' },
  },
  {
    id: 'fire-fix-starter',
    title: "Ember's Gentle Spray",
    childPoem: 'The little flames forgot they were visitors\nEmber offers cool silver rain\nThe fire curls small like a sleepy kitten\nNow the picnic can laugh and play again',
    parentNote: 'Reminds us that a small worry, met with calm and steady kindness, shrinks until the fun can return for everyone.',
    icon: 'hl.ui.fire',
    source: { kind: 'mission', id: 'fire-fix' },
  },
  {
    id: 'secret-friend',
    title: 'A Friend Appears',
    childPoem: 'In the quiet corner where no one rushed\nYou came back, and came back again\nA tiny whiskered face learned your name\nA friend was waiting for someone who stays',
    parentNote: 'Some friendships begin only when we keep returning to the places others pass by. This sticker remembers the child who notices the unnoticed.',
    icon: 'hl.ui.heart',
    source: { kind: 'secret', id: 'secret-friend' },
  },
  {
    id: 'hidden-light',
    title: 'Light Holds Love',
    childPoem: 'When the day is folded away and the room is still\nA single spark remembers your name\nIt was placed there by hands that love you\nSo even in the dark, you are held in light',
    parentNote: 'A small word of love, hidden like a firefly in the quiet spot, waiting for the child who lingers long enough to find it.',
    icon: 'hl.fx.lightBurst',
    source: { kind: 'secret', id: 'hidden-light' },
  },
  {
    id: 'cluckle-dream',
    title: "Cluckle's Small Town",
    childPoem: 'Cluckle tucks the whole wide world under her wing\nRoofs and rivers, friends and trees\nAll of it glowing, small as a heartbeat\nHeld safe inside one dreaming hen\'s dream — and now yours too',
    parentNote: 'The wonder that the entire town — every mission, every secret — can live inside one small, sleeping heart. Cluckle is the secret keeper; the child who finds her becomes one too.',
    icon: 'hl.char.cluckle',
    source: { kind: 'secret', id: 'cluckle-dream' },
  },
  {
    id: 'meadow-nest',
    title: 'The Meadow Nest',
    childPoem: 'Off the path, in the hush of the grass\nthree small eggs lay warm in a ring\nYou wandered where no one was looking\nand found a soft secret waiting to sing',
    parentNote: 'For the child who steps a little off the trail and finds the small, living wonder that the hurried never see.',
    icon: 'hl.prop.runawayFriend',
    source: { kind: 'secret', id: 'meadow-nest' },
  },
  {
    id: 'lamplighter',
    title: 'The Little Lamp',
    childPoem: 'At the edge of the crossing, the dark felt wide\nso you woke a small lamp with your hand\nNow a warm gold puddle waits on the path\nso no one walks home alone in the land',
    parentNote: 'A tiny act of light at the edge of the dark — the quiet kindness of leaving a lamp on for whoever comes after.',
    icon: 'hl.prop.safetyLantern',
    source: { kind: 'secret', id: 'lamplighter' },
  },
  {
    id: 'garden-cat',
    title: 'The Shy Garden Cat',
    childPoem: 'By a wall where the bikes never stop\na small cat watched with careful eyes\nYou waited, and waited, and waited\nand a purr was your gentle surprise',
    parentNote: 'Some friends only come out for the patient. This remembers the child who slowed down long enough to be trusted.',
    icon: 'hl.prop.bearFriend',
    source: { kind: 'secret', id: 'garden-cat' },
  },
  {
    id: 'message-bottle',
    title: 'A Bottle of Love',
    childPoem: 'Far from the buoys, on the quiet sea\na little bottle bobbed your way\nInside was a note from someone who loves you\nsent across the water to brighten your day',
    parentNote: 'A little message of love sealed in a bottle, waiting on the calm sea for the child who drifts a little off course.',
    icon: 'hl.fx.lightBurst',
    source: { kind: 'secret', id: 'message-bottle' },
  },
  {
    id: 'inverse-dream-starter',
    title: 'Cluckle Dreams Opposites',
    childPoem: 'Sun finds moon, and loud finds quiet\nBig holds hands with small\nCluckle dreams the world in pairs\nand you matched them, one and all',
    parentNote: 'Opposites are how a small mind first sorts a big world. Matching them with Cluckle is gentle logic dressed as a dream.',
    icon: 'hl.prop.inverseMoon',
    source: { kind: 'mission', id: 'inverse-dream' },
  },
  {
    id: 'dream-statues-starter',
    title: 'Merry Sets the Statues',
    childPoem: 'Each little statue has a place to belong\nYou found every one its home\nThe dream garden stands, quiet and proud\nbecause you set each stone',
    parentNote: 'Placing each piece where it belongs — a calm, satisfying order the child built with their own hands.',
    icon: 'hl.prop.statueHen',
    source: { kind: 'mission', id: 'dream-statues' },
  },
  {
    id: 'recycled-inventions-starter',
    title: 'Reed Builds a Gadget',
    childPoem: 'Old scraps no one wanted\nbecame a whirring, happy thing\nYou fit each part in its place\nand made the lost bits sing',
    parentNote: 'Seeing worth in what was thrown away, and the joy of making something whole from spare parts.',
    icon: 'hl.prop.assembledGadget',
    source: { kind: 'mission', id: 'recycled-inventions' },
  },
  {
    id: 'bread-rush-starter',
    title: "Benny's Warm Loaf",
    childPoem: 'Flour and water, yeast and care\nadded gently, one by one\nThe oven hums, the kitchen warms\nand a loaf for a friend is done',
    parentNote: 'Following a recipe in order — patience and sequence, ending in something warm to share.',
    icon: 'hl.prop.breadLoaf',
    source: { kind: 'mission', id: 'bread-rush' },
  },
  {
    id: 'goo-cleanup-starter',
    title: 'Grumble Clears the Goo',
    childPoem: 'The square was sticky, glooped and slow\nGrumble grumbled, then got to work\nSwish and shine, the goo all gone\nand under it — a happy town awoke',
    parentNote: 'Even a grump helps when it matters. The quiet satisfaction of making a messy place clean and kind again.',
    icon: 'hl.prop.cleanPatch',
    source: { kind: 'mission', id: 'goo-cleanup' },
  },
  {
    id: 'frog-flight-starter',
    title: 'Wings Catches a Friend',
    childPoem: 'Up where the lanterns turn to stars\nWings glides through ring on ring\nA little frog was lost up high\nand you brought him home — soft landing',
    parentNote: 'Bravery that is gentle: flying high not to win, but to bring a small lost friend safely down.',
    icon: 'hl.prop.frogFriend',
    source: { kind: 'mission', id: 'frog-flight' },
  },
  {
    id: 'asteroid-blaster-starter',
    title: 'Nova Softens the Sky',
    childPoem: 'The rocks came drifting, dark and near\nNova aimed her foam of light\npoof, poof, poof — soft and sure\nand the sky was calm tonight',
    parentNote: 'Meeting something scary with softness, not force — turning a worry into a gentle, winnable game.',
    icon: 'hl.prop.foamStar',
    source: { kind: 'mission', id: 'asteroid-blaster' },
  },
  {
    id: 'scooter-roundup-starter',
    title: 'Scoot Brings Them Home',
    childPoem: 'One by one they wandered far\nScoot puttered out to find them all\nGentle turns and patient beeps\nand home they came, before nightfall',
    parentNote: 'Patience and care in gathering everyone safely — no rushing, no scolding, just steady kindness.',
    icon: 'hl.prop.scooter',
    source: { kind: 'mission', id: 'scooter-roundup' },
  },
  {
    id: 'safety-lights-starter',
    title: 'Dash Crosses Safely',
    childPoem: 'Wait for the glow, then go go go\nDash knows the careful way\nAcross each street and safely home\nyou helped the whole town stay okay',
    parentNote: 'Looking, waiting, and going at the right moment — a real-world safety habit dressed as a happy dash.',
    icon: 'hl.prop.trafficLight',
    source: { kind: 'mission', id: 'safety-lights' },
  },
  {
    id: 'bike-explorer-starter',
    title: 'Milo Maps the Streets',
    childPoem: 'Around each corner, something new\nMilo pedals, bright and free\nEvery stop a little wonder\nthe whole neighborhood to see',
    parentNote: 'The simple joy of exploring close to home, and noticing the small wonders on every street.',
    icon: 'hl.prop.bikeWaypoint',
    source: { kind: 'mission', id: 'bike-explorer' },
  },
  {
    id: 'treasure-boat-starter',
    title: 'Coral Finds the Treasure',
    childPoem: 'Past every buoy, calm and sure\nCoral steered the gentle sea\nThe chest swung open, golden warm\nand the treasure was — being free',
    parentNote: 'Steady navigation toward a goal, and the quiet idea that the real treasure is the calm, brave journey.',
    icon: 'hl.prop.treasureChest',
    source: { kind: 'mission', id: 'treasure-boat' },
  },
];
