import type { MissionId } from '../types';
import type { SecretId } from '../systems/Secrets';

// Reward lore for the Sticker Book. Each sticker a child collects becomes a small,
// re-readable poem they can revisit with a parent — "I got 3 stars" becomes a little
// story of what that meant. The childPoem/parentNote text was generated by the Grok
// model (best-of-n curated) in the project's warm, wonder-over-praise voice and lightly
// reviewed. Sticker ids match the ones the missions and Secrets actually unlock.

export type StickerSource =
  | { kind: 'mission'; id: MissionId }
  | { kind: 'secret'; id: SecretId };

export type StickerDefinition = {
  /** Matches the id stored in profile.progress.stickers. */
  id: string;
  title: string;
  /** A few short lines a parent reads aloud. No hard words. */
  childPoem: string;
  /** One warm sentence for the grown-up. */
  parentNote: string;
  icon: string;
  source: StickerSource;
};

export const STICKER_DEFINITIONS: StickerDefinition[] = [
  {
    id: 'recycling-run-starter',
    title: 'Rivet Finds Homes',
    childPoem: 'Things got lost on their way\nRivet helps them home\nEach finds the bin that fits\nTown feels right once more',
    parentNote: 'For children who enjoy helping lost things find their way back to the right place.',
    icon: '♻️',
    source: { kind: 'mission', id: 'recycling-run' },
  },
  {
    id: 'house-builder-starter',
    title: 'Brick Builds a Home',
    childPoem: 'First the ground is laid\nThen the walls stand high\nLast the roof comes down\nA house for a friend nearby',
    parentNote: 'It celebrates the slow, satisfying work of building a safe little house, one careful choice after another.',
    icon: '🏠',
    source: { kind: 'mission', id: 'house-builder' },
  },
  {
    id: 'fire-fix-starter',
    title: "Ember's Gentle Spray",
    childPoem: 'Fire wants to dance too long\nEmber sprays with care\nFire goes small and still\nPicnic friends are safe there',
    parentNote: 'A token of the calm attention that turns a small trouble into peace so everyone can keep playing.',
    icon: '💦',
    source: { kind: 'mission', id: 'fire-fix' },
  },
  {
    id: 'secret-friend',
    title: 'A Friend Appears',
    childPoem: 'You looked in the still place\nTwice and then once more\nA small friend saw you looking\nNow a friend is yours',
    parentNote: 'Some friends only show themselves to the child who keeps looking in the quiet places; this marks that kind of noticing.',
    icon: '🐭',
    source: { kind: 'secret', id: 'secret-friend' },
  },
  {
    id: 'hidden-light',
    title: 'Light Holds Love',
    childPoem: 'A light waits in the dark\nIt has your name inside\nSomeone who loves you put it\nSo you know you are loved',
    parentNote: 'The grown-up can write their own words of love here; the sticker is a message waiting in light for the child who finds it.',
    icon: '✨',
    source: { kind: 'secret', id: 'hidden-light' },
  },
  {
    id: 'cluckle-dream',
    title: "Cluckle's Small Town",
    childPoem: 'Cluckle dreams with eyes shut tight\nThe big town becomes small\nShining like stars in her head\nYou can hold it all',
    parentNote: 'The wonder that the whole big town can fit inside one small dream, held safely by Cluckle and by the child who finds it.',
    icon: '🐔',
    source: { kind: 'secret', id: 'cluckle-dream' },
  },
];
