import type { MissionId } from '../types';
import type { SecretId } from '../systems/Secrets';

// Reward lore for the Sticker Book. Each sticker a child collects becomes a small,
// re-readable poem they can revisit with a parent — "I got 3 stars" becomes a little
// story of what that meant. The childPoem/parentNote text was generated by the Grok
// model (best-of-n curated) in the project's warm, wonder-over-praise voice and lightly
// reviewed. Sticker ids match the ones the missions and Secrets actually unlock.

export type StickerSource =
  | { kind: 'mission'; id: MissionId }
  | { kind: 'secret'; id: SecretId };

export type StickerDefinition = {
  /** Matches the id stored in profile.progress.stickers. */
  id: string;
  title: string;
  /** A few short lines a parent reads aloud. No hard words. */
  childPoem: string;
  /** One warm sentence for the grown-up. */
  parentNote: string;
  icon: string;
  source: StickerSource;
};

export const STICKER_DEFINITIONS: StickerDefinition[] = [
  {
    id: 'recycling-run-starter',
    title: 'Rivet Finds Homes',
    childPoem: 'Little things wandered far from their friends\nRivet listens where they belong\nPaper with paper, green with the earth\nThe town tucks them in with a song',
    parentNote: 'A quiet celebration of noticing what is out of place and giving it a gentle place to rest. The kind of helping that makes the world feel cared-for.',
    icon: 'hl.ui.recycle',
    source: { kind: 'mission', id: 'recycling-run' },
  },
  {
    id: 'house-builder-starter',
    title: 'Brick Builds a Home',
    childPoem: 'A patch of earth waits with open arms\nBrick chooses the pieces with care\nWalls rise like a story being told\nA roof closes it warm, and a light appears there',
    parentNote: 'It honors the patient joy of building something real, one thoughtful choice at a time, so someone else has a safe place to be.',
    icon: 'hl.ui.build',
    source: { kind: 'mission', id: 'house-builder' },
  },
  {
    id: 'fire-fix-starter',
    title: "Ember's Gentle Spray",
    childPoem: 'The little flames forgot they were visitors\nEmber offers cool silver rain\nThe fire curls small like a sleepy kitten\nNow the picnic can laugh and play again',
    parentNote: 'Reminds us that a small worry, met with calm and steady kindness, shrinks until the fun can return for everyone.',
    icon: 'hl.ui.fire',
    source: { kind: 'mission', id: 'fire-fix' },
  },
  {
    id: 'secret-friend',
    title: 'A Friend Appears',
    childPoem: 'In the quiet corner where no one rushed\nYou came back, and came back again\nA tiny whiskered face learned your name\nA friend was waiting for someone who stays',
    parentNote: 'Some friendships begin only when we keep returning to the places others pass by. This sticker remembers the child who notices the unnoticed.',
    icon: 'hl.ui.heart',
    source: { kind: 'secret', id: 'secret-friend' },
  },
  {
    id: 'hidden-light',
    title: 'Light Holds Love',
    childPoem: 'When the day is folded away and the room is still\nA single spark remembers your name\nIt was placed there by hands that love you\nSo even in the dark, you are held in light',
    parentNote: 'The sticker that carries a parent\'s own words of love. The grown-up can replace the default with a private message that waits like a firefly for the child who finds the quiet spot.',
    icon: 'hl.fx.lightBurst',
    source: { kind: 'secret', id: 'hidden-light' },
  },
  {
    id: 'cluckle-dream',
    title: "Cluckle's Small Town",
    childPoem: 'Cluckle tucks the whole wide world under her wing\nRoofs and rivers, friends and trees\nAll of it glowing, small as a heartbeat\nHeld safe inside one dreaming hen\'s dream — and now yours too',
    parentNote: 'The wonder that the entire town — every mission, every secret — can live inside one small, sleeping heart. Cluckle is the secret keeper; the child who finds her becomes one too.',
    icon: 'hl.char.cluckle',
    source: { kind: 'secret', id: 'cluckle-dream' },
  },
  {
    id: 'inverse-dream-starter',
    title: 'Cluckle Dreams Opposites',
    childPoem: 'Sun finds moon, and loud finds quiet\nBig holds hands with small\nCluckle dreams the world in pairs\nand you matched them, one and all',
    parentNote: 'Opposites are how a small mind first sorts a big world. Matching them with Cluckle is gentle logic dressed as a dream.',
    icon: 'hl.prop.inverseMoon',
    source: { kind: 'mission', id: 'inverse-dream' },
  },
  {
    id: 'dream-statues-starter',
    title: 'Merry Sets the Statues',
    childPoem: 'Each little statue has a place to belong\nYou found every one its home\nThe dream garden stands, quiet and proud\nbecause you set each stone',
    parentNote: 'Placing each piece where it belongs — a calm, satisfying order the child built with their own hands.',
    icon: 'hl.prop.statueHen',
    source: { kind: 'mission', id: 'dream-statues' },
  },
  {
    id: 'recycled-inventions-starter',
    title: 'Reed Builds a Gadget',
    childPoem: 'Old scraps no one wanted\nbecame a whirring, happy thing\nYou fit each part in its place\nand made the lost bits sing',
    parentNote: 'Seeing worth in what was thrown away, and the joy of making something whole from spare parts.',
    icon: 'hl.prop.assembledGadget',
    source: { kind: 'mission', id: 'recycled-inventions' },
  },
  {
    id: 'bread-rush-starter',
    title: "Benny's Warm Loaf",
    childPoem: 'Flour and water, yeast and care\nadded gently, one by one\nThe oven hums, the kitchen warms\nand a loaf for a friend is done',
    parentNote: 'Following a recipe in order — patience and sequence, ending in something warm to share.',
    icon: 'hl.prop.breadLoaf',
    source: { kind: 'mission', id: 'bread-rush' },
  },
];
